# Generated by Django 4.2.2 on 2023-08-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0010_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
