# Generated by Django 4.2.2 on 2023-08-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0014_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='comment',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
