# Generated by Django 4.2.2 on 2023-07-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_state', models.CharField(choices=[('For Sell', 'For Sell'), ('For Rent', 'For Rent'), ('Featured', 'Featured')], max_length=10)),
                ('property_type', models.CharField(choices=[('Apartament', 'Apartament'), ('Villa', 'Villa'), ('Office', 'Office'), ('Shop', 'Shop'), ('Building', 'Building')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='property_images')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
