# Generated by Django 4.2.2 on 2023-07-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='BaseProperty',
        ),
    ]
