# Generated by Django 4.2.2 on 2023-07-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0002_rename_property_baseproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('num_bedrooms', models.PositiveIntegerField()),
                ('num_batrooms', models.PositiveIntegerField()),
                ('area_sqft', models.PositiveIntegerField()),
                ('floor_number', models.PositiveIntegerField()),
                ('has_balcony', models.BooleanField()),
                ('is_furnished', models.BooleanField()),
                ('has_air_conditioning', models.BooleanField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property_market.baseproperty')),
            ],
        ),
    ]
