# Generated by Django 4.2.2 on 2023-07-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0004_villa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('num_rooms', models.PositiveIntegerField()),
                ('area_sqft', models.PositiveIntegerField()),
                ('floor_number', models.PositiveIntegerField()),
                ('has_parking', models.BooleanField()),
                ('has_lift', models.BooleanField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property_market.baseproperty')),
            ],
        ),
    ]
