# Generated by Django 4.2.2 on 2023-07-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0005_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('area_sqft', models.PositiveIntegerField()),
                ('has_parking', models.BooleanField()),
                ('has_window_display', models.BooleanField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property_market.baseproperty')),
            ],
        ),
    ]
