# Generated by Django 4.2.2 on 2023-07-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0008_alter_baseproperty_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='property_images'),
        ),
    ]
