# Generated by Django 4.2.2 on 2023-07-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0011_alter_baseproperty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
