# Generated by Django 4.2.2 on 2023-07-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0013_alter_baseproperty_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='has_parking',
            new_name='has_ac',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='has_window_display',
            new_name='has_cctv',
        ),
    ]
