# Generated by Django 4.2.2 on 2023-07-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0014_rename_has_parking_shop_has_ac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='num_batrooms',
            new_name='num_bathrooms',
        ),
    ]
