# Generated by Django 4.2.2 on 2023-08-01 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_market', '0015_rename_num_batrooms_apartment_num_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproperty',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
