# Generated by Django 4.2.2 on 2023-08-01 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0016_baseproperty_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproperty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
