# Generated by Django 4.2.2 on 2023-08-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0017_baseproperty_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='garage',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
