# Generated by Django 4.2.2 on 2023-08-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0019_additionalfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproperty',
            name='additional_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
