# Generated by Django 4.2.2 on 2023-08-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0020_baseproperty_additional_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproperty',
            name='additional_fields',
        ),
    ]
