# Generated by Django 4.2.2 on 2023-08-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0021_remove_baseproperty_additional_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalField',
        ),
    ]
