# Generated by Django 4.2.2 on 2023-08-04 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_market', '0023_savedproperty_baseproperty_saved_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproperty',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_market.baseproperty'),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='saved_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedProperties', to=settings.AUTH_USER_MODEL),
        ),
    ]
