# Generated by Django 4.2.2 on 2023-08-05 16:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0026_remove_baseproperty_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproperty',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='property_images'), blank=True, null=True, size=None),
        ),
    ]
