# Generated by Django 4.2.2 on 2023-08-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0027_baseproperty_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='images',
            field=models.ImageField(default=1, upload_to='property_images'),
            preserve_default=False,
        ),
    ]
