# Generated by Django 4.2.2 on 2023-08-05 17:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0029_alter_baseproperty_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='images',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('property_images/1', 'Image 1'), ('property_images/2', 'Image 2'), ('property_images/3', 'Image 3'), ('property_images/4', 'Image 4'), ('property_images/5', 'Image 5')], max_length=1000),
        ),
    ]
