# Generated by Django 4.2.2 on 2023-08-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0030_alter_baseproperty_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Office', 'Office'), ('Shop', 'Shop'), ('Building', 'Building')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('size_sqft', models.IntegerField()),
                ('amenities', models.BooleanField(default=False)),
                ('estimate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
