# Generated by Django 4.2.2 on 2023-08-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0031_propertyestimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyestimate',
            name='location',
        ),
        migrations.AddField(
            model_name='propertyestimate',
            name='balconies',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyestimate',
            name='rooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
