# Generated by Django 4.2.2 on 2023-08-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0032_remove_propertyestimate_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproperty',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseproperty',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
