# Generated by Django 4.2.2 on 2023-08-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_market', '0033_baseproperty_from_date_baseproperty_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
