# Generated by Django 4.2.2 on 2023-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0005_rename_newslwtter_type_adminnewsletterpost_newsletter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnewsletterpost',
            name='image',
            field=models.ImageField(default=1, upload_to='newsletter_images'),
            preserve_default=False,
        ),
    ]
